name: 'Container CI'

on:
  
  push:
    branches:
      - main
    paths:
      - app2/**
  
  pull_request: # [master, next]
    paths:
      - app2/**


jobs:
  

  # FAZER SOMENTE NO PULL ESSE DO DOCKER


  container:
    name: 'Container'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: app2
        shell: bash

    steps:

    - if: github.event_name == 'pull_request'
      name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}    
   
    - name: Check Out Repo 
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      if: github.event_name == 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      if: github.event_name == 'pull_request'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./app2/container
        file: ./app2/container/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app2:${{ steps.buildnumber.outputs.build_number }}
